releases:


  - name: kafka
    chart: kafka-chart
    values:
      - values/kafka-values.yaml
  - name: discovery-service
    chart: backend-chart
    values:
      - values/discovery-service-values.yaml
    needs:

  - name: orders-service
    chart: backend-chart
    values:
      - values/order-service-values.yaml
    needs:
      - kafka
      - discovery-service


#  - name: postgres
#    chart: postgress-chart-keycloak
#    values:
#      - values/postgress-keycloak-values.yaml
#
#  - name: keycloak
#    chart: keycloak-chart
#    values:
#          - values/keycloak-values.yaml
#    needs:
#      - postgres
