releases:
  - name: kafka
    chart: kafka-chart
    values:
      - values/kafka-values.yaml

  - name: mongodb
    chart: mongo-chart
    values:
      - values/mongodb-values.yaml

  - name: mongo-express
    chart: mongo-chart
    values:
      - values/mongo-express-values.yaml
    needs:
      - mongodb


  - name: orders-service
    chart: backend-chart
    values:
      - values/order-service-values.yaml
    needs:
      - kafka

  - name: stock-service
    chart: backend-chart
    values:
      - values/stock-service-values.yaml
    needs:
      - mongodb
      - kafka

  - name: shipment-service
    chart: backend-chart
    values:
      - values/shipment-service-values.yaml
    needs:
      - kafka

  - name: payment-service
    chart: backend-chart
    values:
      - values/payment-service-values.yaml
    needs:
      - kafka
#
  - name: customer-service
    chart: backend-chart
    values:
      - values/customer-service-values.yaml
#    needs:
#      - mongodb
#      - kafka

#  - name: criditcard-service
#    chart: backend-chart
#    values:
#      - values/criditcard-service-values.yaml
#
#  - name: notification-service
#    chart: notification-chart
#    values:
#      - values/notification-service-values.yaml

#  - name: postgres
#    chart: postgress-chart-keycloak
#    values:
#      - values/postgress-keycloak-values.yaml
#
#  - name: keycloak
#    chart: keycloak-chart
#    values:
#          - values/keycloak-values.yaml
#    needs:
#      - postgres
