depName: credit-card-service-dep
replicasNum: 1
podName: credit-card-service-pod
imageName: soulaimandockerhub/credit-card-service
imageVersion: v1.0
containerName: credit-card-service-container
containerPort: 8080
containerEnvVar:
  - name: DISCOVERY_SERVICE_URL
    value: "http://discovery-service-svc:8761/eureka"
  - name: SERVER_PORT
    value: "8080"
serviceName: credit-card-service-svc
servicePort: 8080
serviceType: NodePort
nodePort: 30070