depName: orders-service-dep
replicasNum: 1
podName: orders-service-pod
imageName: soulaimandockerhub/order-service
imageVersion: v1.3
containerName: orders-service-container
containerPort: 8080
containerEnvVar:
  - name: DISCOVERY_SERVICE_URL
    value: "http://discovery-service-svc:8761/eureka"
  - name: SERVER_PORT
    value: "8080"
  - name: BOOTSRAP_KAFKA_SERVER
    value: "kafka-0.kafka-headless.default.svc.cluster.local"
  - name: SERVER1_PORT
    value: "9192"
  - name: KEYCLOAK_SERVER
    value: "http://10.10.9.137:30050"
  - name: KEYCLOAK_REALM
    value: "ecom-realm"
  - name: KEYCLOAK_CLIENT
    value: "ecom-app"
serviceName: orders-service-svc
servicePort: 8080
serviceType: NodePort
nodePort: 30040