depName: orders-service-dep
replicasNum: 1
podName: orders-service-pod
imageName: soulaimandockerhub/order-service
imageVersion: v2.2
containerName: orders-service-container
containerPort: 8080
containerEnvVar:
  - name: PRODUCT_SERVICE_URL
    value: "stock-service-svc:8080"
  - name: CUSTOMER_SERVICE_URL
    value: "customer-service-svc:8080"
  - name: SERVER_PORT
    value: "8080"
  - name: BOOTSRAP_KAFKA_SERVER
    value: "kafka-0.kafka-headless.default.svc.cluster.local"
  - name: SERVER1_PORT
    value: "9192"
  - name: KEYCLOAK_SERVER
    value: "http://10.10.9.137:30050"
  - name: KEYCLOAK_REALM
    value: "ecom-realm"
  - name: KEYCLOAK_CLIENT
    value: "ecom-app"
  - name: MONGODB_HOST
    value: "mongodb-svc"
  - name: MONGODB_PORT
    value: "27017"
  - name: SERVER_PORT
    value: "8080"
  - name: MONGODB_USERNAME
    value: "admin"
  - name: MONGODB_PASSWORD
    value: "password"
serviceName: orders-service-svc
servicePort: 8080
serviceType: NodePort
nodePort: 30040