depName: payment-service-dep
replicasNum: 1
podName: payment-service-pod
imageName: soulaimandockerhub/payement-service
imageVersion: v1.0
containerName: payment-service-container
containerPort: 8080
containerEnvVar:
  - name: DISCOVERY_SERVICE_URL
    value: "http://discovery-service-svc:8761/eureka"
  - name: SERVER_PORT
    value: "8080"
  - name: BOOTSRAP_KAFKA_SERVER
    value: "kafka-0.kafka-headless.default.svc.cluster.local"
  - name: SERVER1_PORT
    value: "9192"
serviceName: payment-service-svc
servicePort: 8080
serviceType: NodePort
nodePort: 30030