depName: shipment-service-dep
replicasNum: 1
podName: shipment-service-pod
imageName: soulaimandockerhub/shipment-service
imageVersion: v2.2
containerName: shipment-service-container
containerPort: 8080
containerEnvVar:
  - name: SERVER_PORT
    value: "8080"
  - name: BOOTSRAP_KAFKA_SERVER
    value: "kafka-0.kafka-headless.default.svc.cluster.local"
  - name: SERVER1_PORT
    value: "9192"
serviceName: shipment-service-svc
servicePort: 8080