depName: stock-service-dep
replicasNum: 1
podName: stock-service-pod
imageName: soulaimandockerhub/stock-service
imageVersion: v2.1
containerName: stock-service-container
containerPort: 8080
containerEnvVar:
  - name: DISCOVERY_SERVICE_URL
    value: "http://discovery-service-svc:8761/eureka"
  - name: MONGODB_HOST
    value: "mongodb-svc"
  - name: MONGODB_PORT
    value: "27017"
  - name: SERVER_PORT
    value: "8080"
  - name: MONGODB_USERNAME
    value: "admin"
  - name: MONGODB_PASSWORD
    value: "password"
  - name: KEYCLOAK_SERVER
    value: "http://10.10.9.137:30050"
  - name: KEYCLOAK_REALM
    value: "ecom-realm"
  - name: KEYCLOAK_CLIENT
    value: "ecom-app"
  - name: BOOTSRAP_KAFKA_SERVER
    value: "kafka-0.kafka-headless.default.svc.cluster.local"
  - name: SERVER1_PORT
    value: "9192"
serviceName: stock-service-svc
servicePort: 8080
serviceType: NodePort
nodePort: 30010